networks:
  ai_network:
    driver: bridge

services:
  heygem-tts:
    image: guiji2025/fish-speech-ziming
    container_name: heygem-tts
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
    ports:
      - '18180:8080'
    volumes:
      - ~/heygem_data/voice/data:/code/data
    command: /bin/bash -c "/opt/conda/envs/python310/bin/python3 tools/api_server.py --listen 0.0.0.0:8080"
    networks:
      - ai_network

  heygem-tts-file-server:
    image: node:18-alpine
    container_name: heygem-tts-file-server
    restart: always
    volumes:
      - ~/heygem_data/voice/data:/app/data
      - /Users/colin/workspace/HeyGem.ai/deploy/file-server:/app/src
    working_dir: /app
    ports:
      - '18181:18181'
    command: sh -c "cd /app && npm install express multer cors && node src/index.js 18181 /app/data"
    networks:
      - ai_network

  heygem-gen-video:
    image: guiji2025/heygem.ai
    container_name: heygem-gen-video
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - ~/heygem_data/face2face:/code/data
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '8g'
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network

  heygem-face2face-file-server:
    image: node:18-alpine
    container_name: heygem-face2face-file-server
    restart: always
    volumes:
      - ~/heygem_data/face2face:/app/data
      - /Users/colin/workspace/HeyGem.ai/deploy/file-server:/app/src
    working_dir: /app
    ports:
      - '8384:8384'
    command: sh -c "cd /app && npm install express multer cors && node src/index.js 8384 /app/data"
    networks:
      - ai_network
